import numpy as np
array = np.random.randint(1,99, size=(5, 5), dtype=int)
np.mean(array, axis=1)
print("Array: ")
print(array)
print("Number in row 2, column 3: ")
print(array[1][2])
print("Sum of all elements: ")
print(np.sum(array))
print("Mean of each row: ")
print(np.mean(array, axis=1))
print("Maximum value in each column: ")
print(np.max(array, axis=0))
